
server:
  port: 8910

spring:
  application:
    name: boot-oss
  #mvc
  mvc:
    view:
      prefix: /
      suffix: .html
#  resources:
#    static-locations: classpath:/static/
      
#  thymeleaf:
#    prefix: classpath:/static/
    

  #激活哪一个环境的配置文件
  profiles:
    active: dev

oss.root.path: D:/run/oss/
oss.domain.prefix: http://localhost:8910/


---
#开发环境配置

spring:
  profiles: dev

oss.root.path: D:/run/oss/
oss.domain.prefix: http://localhost:8910/



---
#开发环境配置

spring:
  profiles: prod

oss.root.path: /data/oss/
oss.domain.prefix: http://xxx.com/
 